### Part I: Set up Google Drive Environment



In [46]:
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [47]:
file = drive.CreateFile({'id':'####'}) # put your id 
file.GetContentFile('review_data.tsv')  

### Part II: Load the data and libraries

In [48]:
import numpy as np
import pandas as pd
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
# download punctuation package
nltk.download('punkt') 
# download stopwords package
nltk.download('stopwords') 

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [49]:
# Load the data into dataframe
df = pd.read_csv('review_data.tsv', sep = '\t', error_bad_lines = False)

b'Skipping line 8704: expected 15 fields, saw 22\nSkipping line 16933: expected 15 fields, saw 22\nSkipping line 23726: expected 15 fields, saw 22\n'
b'Skipping line 85637: expected 15 fields, saw 22\n'
b'Skipping line 132136: expected 15 fields, saw 22\nSkipping line 158070: expected 15 fields, saw 22\nSkipping line 166007: expected 15 fields, saw 22\nSkipping line 171877: expected 15 fields, saw 22\nSkipping line 177756: expected 15 fields, saw 22\nSkipping line 181773: expected 15 fields, saw 22\nSkipping line 191085: expected 15 fields, saw 22\nSkipping line 196273: expected 15 fields, saw 22\nSkipping line 196331: expected 15 fields, saw 22\n'
b'Skipping line 197000: expected 15 fields, saw 22\nSkipping line 197011: expected 15 fields, saw 22\nSkipping line 197432: expected 15 fields, saw 22\nSkipping line 208016: expected 15 fields, saw 22\nSkipping line 214110: expected 15 fields, saw 22\nSkipping line 244328: expected 15 fields, saw 22\nSkipping line 248519: expected 15 fields,

In [50]:
df.head()

marketplace  ...  review_date
0          US  ...   2015-08-31
1          US  ...   2015-08-31
2          US  ...   2015-08-31
3          US  ...   2015-08-31
4          US  ...   2015-08-31

[5 rows x 15 columns]

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960204 entries, 0 to 960203
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   marketplace        960204 non-null  object
 1   customer_id        960204 non-null  int64 
 2   review_id          960204 non-null  object
 3   product_id         960204 non-null  object
 4   product_parent     960204 non-null  int64 
 5   product_title      960202 non-null  object
 6   product_category   960204 non-null  object
 7   star_rating        960204 non-null  int64 
 8   helpful_votes      960204 non-null  int64 
 9   total_votes        960204 non-null  int64 
 10  vine               960204 non-null  object
 11  verified_purchase  960204 non-null  object
 12  review_headline    960197 non-null  object
 13  review_body        960056 non-null  object
 14  review_date        960200 non-null  object
dtypes: int64(5), object(10)
memory usage: 109.9+ MB


In [52]:
# Remove missing value, since we can't impute missing value for review
df.dropna(subset=['review_body'], inplace=True)

In [53]:
df.reset_index(inplace=True, drop = True) # reset the index

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960056 entries, 0 to 960055
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   marketplace        960056 non-null  object
 1   customer_id        960056 non-null  int64 
 2   review_id          960056 non-null  object
 3   product_id         960056 non-null  object
 4   product_parent     960056 non-null  int64 
 5   product_title      960054 non-null  object
 6   product_category   960056 non-null  object
 7   star_rating        960056 non-null  int64 
 8   helpful_votes      960056 non-null  int64 
 9   total_votes        960056 non-null  int64 
 10  vine               960056 non-null  object
 11  verified_purchase  960056 non-null  object
 12  review_headline    960049 non-null  object
 13  review_body        960056 non-null  object
 14  review_date        960052 non-null  object
dtypes: int64(5), object(10)
memory usage: 109.9+ MB


In [55]:
# Subset first 5000 rows for my analysis
data = df.loc[:4999, 'review_body'].tolist()

In [56]:
data

['Absolutely love this watch! Get compliments almost every time I wear it. Dainty.',
 'I love this watch it keeps time wonderfully.',
 'Scratches',
 'It works well on me. However, I found cheaper prices in other places after making the purchase',
 "Beautiful watch face.  The band looks nice all around.  The links do make that squeaky cheapo noise when you swing it back and forth on your wrist which can be embarrassing in front of watch enthusiasts.  However, to the naked eye from afar, you can't tell the links are cheap or folded because it is well polished and brushed and the folds are pretty tight for the most part.<br /><br />I love the new member of my collection and it looks great.  I've had it for about a week and so far it has kept good time despite day 1 which is typical of a new mechanical watch",
 'i love this watch for my purpose, about the people complaining should of done their research better before buying. dumb people.',
 'for my wife and she loved it, looks great and a 

### Part III: Tokenizing and Stemming

In [57]:
# Use nltk's English stopwords 
stopwords = nltk.corpus.stopwords.words('english')


In [58]:
# Append self-created stopwords
stopwords.append("'s")
stopwords.append("'m")
stopwords.append("br")
stopwords.append("watch")


In [59]:
print ("We use " + str(len(stopwords)) + " stop-words from nltk library")
print (stopwords[:10])

We use 183 stop-words from nltk library
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


Define a function to tokenize and stem our reviews

In [60]:
from nltk.stem.snowball import SnowballStemmer

stemmer = SnowballStemmer("english")

# Define a function to tokenize and stem
def tokenization_and_stemming(text):
  tokens = []
  # exclude stop words and tokenize the document, generate a list of string
  for word in nltk.word_tokenize(text):
    if word.lower() not in stopwords:
      tokens.append(word.lower())
    
  filtered_tokens = []
  # filter out any tokens that are not words, i.e numbers, emoji etc
  for token in tokens:
    if token.isalpha(): # just keep the tokens that are words
      filtered_tokens.append(token)
  # stemming
  stems = [stemmer.stem(t) for t in filtered_tokens]
  return stems

In [61]:
tokenization_and_stemming(data[0])

['absolut',
 'love',
 'get',
 'compliment',
 'almost',
 'everi',
 'time',
 'wear',
 'dainti']

### Part IV: TF-IDF

In [62]:
# Build tf-idf vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_model = TfidfVectorizer(max_df = 0.99, max_features = 1000,
                              min_df = 0.01, stop_words = 'english', 
                              use_idf = True, tokenizer = tokenization_and_stemming, 
                              ngram_range = (1,1))



In [63]:
tfidf_matrix = tfidf_model.fit_transform(data) 

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [64]:
print ("In total, there are " + str(tfidf_matrix.shape[0]) + \
       " reviews and " + str(tfidf_matrix.shape[1]) + " terms.")

In total, there are 5000 reviews and 234 terms.


In [65]:
tfidf_matrix.toarray() 

array([[0.        , 0.52862754, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [66]:
# Save terms identified by tf-idf
tf_selected_words = tfidf_model.get_feature_names()

In [67]:
tf_selected_words

['abl',
 'absolut',
 'accur',
 'actual',
 'adjust',
 'alarm',
 'alreadi',
 'alway',
 'amaz',
 'amazon',
 'anoth',
 'anyth',
 'appear',
 'arriv',
 'attract',
 'automat',
 'awesom',
 'bad',
 'band',
 'batteri',
 'beauti',
 'best',
 'better',
 'big',
 'bit',
 'black',
 'blue',
 'bought',
 'box',
 'bracelet',
 'brand',
 'break',
 'broke',
 'button',
 'buy',
 'ca',
 'came',
 'case',
 'casio',
 'chang',
 'cheap',
 'clasp',
 'classi',
 'clear',
 'clock',
 'color',
 'come',
 'comfort',
 'compliment',
 'cool',
 'cost',
 'coupl',
 'crystal',
 'cute',
 'dark',
 'date',
 'daughter',
 'day',
 'deal',
 'definit',
 'deliveri',
 'design',
 'dial',
 'differ',
 'difficult',
 'digit',
 'disappoint',
 'display',
 'durabl',
 'easi',
 'easili',
 'eleg',
 'end',
 'everi',
 'everyday',
 'everyth',
 'exact',
 'excel',
 'expect',
 'expens',
 'face',
 'far',
 'fast',
 'favorit',
 'featur',
 'feel',
 'fell',
 'fine',
 'fit',
 'function',
 'gave',
 'gift',
 'glass',
 'goe',
 'gold',
 'good',
 'got',
 'great',
 'ha

### Part V: Topic Modelling - Latent Dirichlet Allocation

In [68]:
# Use LDA for clustering
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components = 5) # Divide to 5 topics

In [69]:
# document topic matrix for tfidf_matrix _lda
lda_output = lda.fit_transform(tfidf_matrix)
print(lda_output.shape)
print(lda_output)

(5000, 5)
[[0.06165284 0.05942584 0.05995579 0.50961369 0.30935185]
 [0.090843   0.08453656 0.08853776 0.65022976 0.08585292]
 [0.10224939 0.10000324 0.59774175 0.10000292 0.10000271]
 ...
 [0.1028781  0.10007366 0.10155001 0.10000084 0.59549739]
 [0.06078251 0.22833713 0.22431944 0.42366207 0.06289885]
 [0.08425744 0.0841967  0.08421    0.6629514  0.08438446]]


In [70]:
# topic and words matrix
topic_word = lda.components_
print(topic_word.shape)
print(topic_word)

(5, 234)
[[17.88321039  7.49263141 18.90987954 ... 14.1376626  58.22048214
  53.7196922 ]
 [ 0.20035393  0.20077259  0.2037901  ...  0.20132927  0.20179274
   0.29214242]
 [ 2.73518371  0.2007668   6.68571367 ...  0.20280516 27.65478098
   0.20407801]
 [ 0.20044395  0.20465019  0.20190757 ...  0.20043281  1.36864484
   0.2124158 ]
 [ 1.33559966 21.83239455  0.56706267 ... 23.86837039  6.95970859
   8.60340028]]


In [71]:
# Create column names
topic_names = ["Topic" + str(i) for i in range(lda.n_components)]
# Create index names
doc_names = ["Doc" + str(i) for i in range(len(data))]
df_document_topic = pd.DataFrame(np.round(lda_output, 2), columns = topic_names, index = doc_names)


In [72]:
df_document_topic.head()

Topic0  Topic1  Topic2  Topic3  Topic4
Doc0    0.06    0.06    0.06    0.51    0.31
Doc1    0.09    0.08    0.09    0.65    0.09
Doc2    0.10    0.10    0.60    0.10    0.10
Doc3    0.76    0.06    0.06    0.06    0.06
Doc4    0.41    0.04    0.46    0.04    0.04

In [73]:
# Get dominant topic for each document
topic = np.argmax(df_document_topic.values, axis = 1)
df_document_topic['topic'] = topic
df_document_topic.head(10)

Topic0  Topic1  Topic2  Topic3  Topic4  topic
Doc0    0.06    0.06    0.06    0.51    0.31      3
Doc1    0.09    0.08    0.09    0.65    0.09      3
Doc2    0.10    0.10    0.60    0.10    0.10      2
Doc3    0.76    0.06    0.06    0.06    0.06      0
Doc4    0.41    0.04    0.46    0.04    0.04      2
Doc5    0.69    0.07    0.07    0.09    0.08      0
Doc6    0.06    0.06    0.06    0.07    0.74      4
Doc7    0.75    0.06    0.06    0.06    0.06      0
Doc8    0.81    0.05    0.05    0.05    0.05      0
Doc9    0.77    0.06    0.06    0.06    0.06      0

In [74]:
df_document_topic['topic'].value_counts().to_frame()

topic
0   2009
2    954
1    739
4    686
3    612

In [75]:
# topic word matrix
print(lda.components_)
# topic-word matrix
df_topic_words = pd.DataFrame(lda.components_)

# column and index
df_topic_words.columns = tfidf_model.get_feature_names()
df_topic_words.index = topic_names
df_topic_words.head()



[[17.88321039  7.49263141 18.90987954 ... 14.1376626  58.22048214
  53.7196922 ]
 [ 0.20035393  0.20077259  0.2037901  ...  0.20132927  0.20179274
   0.29214242]
 [ 2.73518371  0.2007668   6.68571367 ...  0.20280516 27.65478098
   0.20407801]
 [ 0.20044395  0.20465019  0.20190757 ...  0.20043281  1.36864484
   0.2124158 ]
 [ 1.33559966 21.83239455  0.56706267 ... 23.86837039  6.95970859
   8.60340028]]


abl    absolut      accur  ...      worth      wrist       year
Topic0  17.883210   7.492631  18.909880  ...  14.137663  58.220482  53.719692
Topic1   0.200354   0.200773   0.203790  ...   0.201329   0.201793   0.292142
Topic2   2.735184   0.200767   6.685714  ...   0.202805  27.654781   0.204078
Topic3   0.200444   0.204650   0.201908  ...   0.200433   1.368645   0.212416
Topic4   1.335600  21.832395   0.567063  ...  23.868370   6.959709   8.603400

[5 rows x 234 columns]

In [76]:
# print top n keywords for each topic
def print_topic_words(tfidf_model, lda_model, n_words):
    words = np.array(tfidf_model.get_feature_names())
    topic_words = []
    # for each topic, we have words weight
    for topic_words_weights in lda_model.components_:
        top_words = topic_words_weights.argsort()[::-1][:n_words]
        topic_words.append(words.take(top_words))
    return topic_words


In [77]:
topic_keywords = print_topic_words(tfidf_model = tfidf_model, lda_model = lda, n_words=15)

df_topic_words = pd.DataFrame(topic_keywords)
df_topic_words.columns = ['Word' + str(i) for i in range(df_topic_words.shape[1])]
df_topic_words.index = ['Topic ' + str(i) for i in range(df_topic_words.shape[0])]
df_topic_words

Word0    Word1    Word2    Word3  ...  Word11  Word12   Word13 Word14
Topic 0   time     look     like     band  ...     use     day    great  wrist
Topic 1   good  product   expect  qualiti  ...    nice  pictur    happi   valu
Topic 2   nice    excel     look    cheap  ...     big    eleg    wrist  price
Topic 3   love   beauti  perfect     gift  ...  bought    item    pleas    lot
Topic 4  great     look   awesom     love  ...     son    ship  batteri    got

[5 rows x 15 columns]

### Part VI K-means clustering

In [78]:
# k- means clustering
from sklearn.cluster import KMeans
num_clusters = 5
# number of clusters
km = KMeans(n_clusters = num_clusters)
km.fit(tfidf_matrix)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [79]:
clusters = km.labels_.tolist()


#### Analyze K-means Result

In [81]:
# Create DataFrame films from all of the input files
product = {'review': df[:5000].review_body, 'cluster': clusters}
frame = pd.DataFrame(product, columns = ['review', 'cluster'])

In [82]:
frame.head(10)

review  cluster
0  Absolutely love this watch! Get compliments al...        4
1       I love this watch it keeps time wonderfully.        4
2                                          Scratches        1
3  It works well on me. However, I found cheaper ...        1
4  Beautiful watch face.  The band looks nice all...        1
5  i love this watch for my purpose, about the pe...        1
6  for my wife and she loved it, looks great and ...        2
7  I was about to buy this thinking it was a Swis...        1
8  Watch is perfect. Rugged with the metal &#34;B...        2
9  Great quality and build.<br />The motors are r...        1

In [83]:
print ("Number of reviews included in each cluster:")
frame['cluster'].value_counts().to_frame()

Number of reviews included in each cluster:


cluster
1     3458
2      502
4      438
0      315
3      287

In [84]:
# Check the centers of each cluster
km.cluster_centers_

array([[0.        , 0.        , 0.00104262, ..., 0.00224199, 0.00511506,
        0.00101252],
       [0.00591508, 0.00462636, 0.00658705, ..., 0.00911419, 0.02429341,
        0.01570639],
       [0.00106122, 0.        , 0.00234634, ..., 0.00575306, 0.00708565,
        0.01143231],
       [0.        , 0.        , 0.00229825, ..., 0.00391981, 0.00460418,
        0.        ],
       [0.00083955, 0.02952797, 0.00142566, ..., 0.00313806, 0.00664191,
        0.00379238]])

In [85]:
km.cluster_centers_.shape

(5, 234)

In [86]:
#Denotes the importances of each items in centroid
# Sort it in decreasing-order and get the top k items
order_centroids = km.cluster_centers_.argsort()[:,::-1]


In [87]:
order_centroids.shape

(5, 234)

In [88]:
Cluster_keywords_summary = {}
for i in range(num_clusters):
    print ("Cluster " + str(i) + " words:", end='')
    Cluster_keywords_summary[i] = []
    for ind in order_centroids[i, :6]: #replace 5 with n words per cluster
        Cluster_keywords_summary[i].append(tf_selected_words[ind])
        print (tf_selected_words[ind] + ",", end='')
    print ()
    
    cluster_reviews = frame[frame.cluster==i].review.tolist()
    print ("Cluster " + str(i) + " reviews (" + str(len(cluster_reviews)) + " reviews): ")
    print (", ".join(cluster_reviews))
    print ()

Cluster 0 words:good,product,recommend,look,price,qualiti,
Cluster 0 reviews (315 reviews): 
very good, It's a good value, and a good functional watch strap.  It's super wide though, and takes more space on the wrist than I'd like., very good, Excellent product and seller very good service, Good value product, Looks good. Not bulky. Keeps good time., good, works good so far., good, very good., Good, Good quality with a reasonable price, good quality. on time, Good looking and smart! Works like a charm., Good for work, Very stylish; looks good on my wrist. Lots of compliments. A good buy., Good Product & good seller, It's not keeping good time, good, it 's good watch . I wear when I work. it light and look style.thanks, its good, Good!, good, Good, good, A little big, Good!, so far so good,  it is a good looking watch.  With all the necessary features one needs.  only drawback is the date window, the date is awfully small., Very good, very good, Good, Good product, If looking for a FUN 